/// Flutter icons AmazingIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AmazingIcon
///      fonts:
///       - asset: fonts/AmazingIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class AmazingIcon {
  AmazingIcon._();

  static const _kFontFam = 'AmazingIcon';
  static const _kFontPkg = null;

  static const IconData arrow_left_line = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_right_s_line = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_drop_right_line = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_drop_down_line = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_down_s_line = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock_password_line = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_fill = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alert_line = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_6_line = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopping_cart_line = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_line = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_2_line = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat_1_line = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close_fill = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close_line = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData global_line = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emotion_sad_line = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData list_settings_fill = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more_2_line = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more_2_fill = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bar_chart_line = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_line = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData account_circle_line = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData refresh_line = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checkbox_circle_line = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData at_line = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone_line = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map_pin_2_line = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData community_line = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete_bin_6_line = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData repeat_2_line = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit_2_line = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData archive_line = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
