List globalEmployees,
    globalSales,
    globalSites,
    globalProducts,
    globalPurchases,
    globalNotifications,
    globalSuppliers,
    globalClients,
    globalStats,
    globalContacts,
    globalCategories,
    globalFirstTeam;
